#!/usr/bin/env python3
"""Regenerate the runtime table or audit a compiled bridge (not bundled in app)."""
import argparse
from pathlib import Path

IDENTIFIERS = [
    ('Coordinator', '_UIContextMenuLiquidMorphPresentationAnimation'),
    ('Initialize', 'initWithUIController:previousAnimation:'),
    ('Start', 'performTransition'),
    ('Alongside', 'setPresentationAlongsideAnimator:'),
    ('From', 'resolvedSourcePreview'),
    ('Attachment', 'morphPreviewFromAttachmentPoint'),
    ('Pivot', 'sourcePreview'),
    ('UsesDestination', 'sourcePreviewMorphsToMenu'),
    ('Content', 'contentPlatterView'),
    ('Accessories', '_accessoryViews'),
    ('Dragging', '_isDismissingToDrag'),
    ('Background', '_setBackgroundVisible:'),
    ('Layout', 'currentLayout'),
    ('Flock', 'flocker'),
    ('Menu', 'menuView'),
    ('Host', 'platterContainerView'),
    ('Detached', 'platterTransitionView'),
    ('EndHiding', 'endSourcePreviewHidingIfNeeded'),
    ('Destination', 'rootListView'),
    ('RunAnimations', 'performAllAnimations'),
    ('RunCompletions', 'performAllCompletions'),
    ('Visibility', '_vendAssertionForOverrideAlpha:'),
]
TABLE = Path(__file__).resolve().parents[3] / "submodules/TelegramUI/Components/LensTransition/Bridge/Sources/Identifiers.inc"

def generated():
    result = "// Generated by prototypes/ContextMenuMorph/Tools/runtime_identifiers.py\n"
    result += "typedef NS_ENUM(NSUInteger, LTKey) {\n"
    result += "".join("    LT" + key + ",\n" for key, _ in IDENTIFIERS)
    result += "    LTKeyCount\n};\nstatic const volatile uint8_t LTNames[LTKeyCount][64] = {\n"
    for _, name in IDENTIFIERS:
        assert len(name.encode()) < 64
        result += "    {" + ", ".join(str(byte ^ 0xa7) for byte in name.encode() + b"\0") + "},\n"
    return result + "};\n"

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--binary", type=Path)
    args = parser.parse_args()
    if args.write:
        TABLE.write_text(generated())
    else:
        assert TABLE.read_text() == generated(), "Identifier table is stale"
    if args.binary:
        data = args.binary.read_bytes()
        forbidden = [name for _, name in IDENTIFIERS] + ["$s5UIKit23_UILiquidMorphAnimation", "_TtC5UIKit23_UILiquidMorphAnimation"]
        found = [name for name in forbidden if name.encode() in data]
        assert not found, "Unencoded identifiers: " + ", ".join(found)
        print("PASS: no private bridge identifiers or legacy Swift symbols in " + str(args.binary))
